# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calcu.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sum = QtWidgets.QPushButton(self.centralwidget)
        self.sum.setGeometry(QtCore.QRect(230, 230, 93, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.sum.setFont(font)
        self.sum.setStyleSheet("background-colour:cyan;color:white;    ")
        self.sum.setObjectName("BUTTON1")
        self.product = QtWidgets.QPushButton(self.centralwidget)
        self.product.setGeometry(QtCore.QRect(230, 300, 93, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.product.setFont(font)
        self.product.setObjectName("BUTTON4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(300, 370, 93, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.diff = QtWidgets.QPushButton(self.centralwidget)
        self.diff.setGeometry(QtCore.QRect(360, 230, 93, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.diff.setFont(font)
        self.diff.setStyleSheet("background-color: gray;color:black;\n"
                                "")
        self.diff.setObjectName("BUTTON2")
        self.divide = QtWidgets.QPushButton(self.centralwidget)
        self.divide.setGeometry(QtCore.QRect(360, 300, 93, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.divide.setFont(font)
        self.divide.setObjectName("BUTTON5")
        self.calculator = QtWidgets.QLabel(self.centralwidget)
        self.calculator.setGeometry(QtCore.QRect(270, 10, 121, 51))
        self.calculator.setObjectName("calculator")
        self.input1 = QtWidgets.QLineEdit(self.centralwidget)
        self.input1.setGeometry(QtCore.QRect(230, 50, 211, 31))
        self.input1.setObjectName("input1")
        self.input2 = QtWidgets.QLineEdit(self.centralwidget)
        self.input2.setGeometry(QtCore.QRect(230, 110, 211, 31))
        self.input2.setObjectName("input2")
        self.output = QtWidgets.QLineEdit(self.centralwidget)
        self.output.setGeometry(QtCore.QRect(230, 170, 211, 31))
        self.output.setObjectName("output")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.sum.clicked.connect(self.add)  # connecting the function sum to main window
        self.diff.clicked.connect(self.subtract)
        self.product.clicked.connect(self.multiply)
        self.divide.clicked.connect(self.division)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.sum.setText(_translate("MainWindow", "+"))
        self.product.setText(_translate("MainWindow", "*"))
        self.pushButton.setText(_translate("MainWindow", "="))
        self.diff.setText(_translate("MainWindow", "-"))
        self.divide.setText(_translate("MainWindow", "/"))
        self.calculator.setText(_translate("MainWindow", "Simpe Calculator "))
        self.input1.setPlaceholderText(_translate("MainWindow", "value1"))
        self.input2.setPlaceholderText(_translate("MainWindow", "value2"))
        self.output.setPlaceholderText(_translate("MainWindow", "result"))

    def add(self):
        x1 = self.input1.text()
        y1 = self.input2.text()
        z1 = int(x1) + int(y1)
        self.output.setText("sum: " + str(z1))

    def subtract(self):
        x1 = self.input1.text()
        y1 = self.input2.text()
        z1 = int(x1) - int(y1)
        self.output.setText("diff: " + str(z1))

    def multiply(self):
        x1 = self.input1.text()
        y1 = self.input2.text()
        z1 = int(x1) * int(y1)
        self.output.setText("product: " + str(z1))

    def division(self):
        x1 = self.input1.text()
        y1 = self.input2.text()
        z1 = int(x1) / int(y1)
        self.output.setText("divide: " + str(z1))



if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
